- api/hms/app/controllers/building_controller.py
- api/hms/app/models/bulding_model.py
- api/hms/app/views/building_view.py
- api/hms/routes.py
**Changes:**
- add building resource
- add building routes
> DLS-MSD-APP-00022 : MSD API - Create Resource for Building

- api/hms/app/controllers/room_controller.py
- api/hms/app/models/room_model.py
- api/hms/app/views/room_view.py
- api/hms/routes.py
**Changes:**
- add room resource
- add room routes
> DLS-MSD-APP-00023 : MSD API - Create Resource for Room

- api/hms/app/controllers/user_controller.py
- api/hms/app/models/user_model.py
- api/hms/routes.py
**Changes:**
- user model: fix reconnection issue and organize functions ( get by id , auth )
- user controller: organize function ( get all, get by id, auth )
- add routes: /users and /user/<string:id>
> DLS-MSD-APP-00020: MSD API - Cleanup Resource for User to include reconnection module

- api/hms/app/controllers/room_bedspace_controller.py
- api/hms/app/models/room_bedspace_model.py
- api/hms/app/views/room_bedspace_view.py
- api/hms/routes.py
**Changes:**
- add room_bedspace resource
- add room_bedspace routes
> DLS-MSD-APP-00024 : MSD API - Create Resource for Room Bedspace

- api/hms/app/utils/database.py
**Changes:**
- add insert mysql execute
- add update mysql execute
- add delete mysql execute
> DLS-MSD-APP-00029 : MSD API - Include CRUD in utililty database

- src/pages/projects/home.js
**Changes:**
- add admin home page
> DLS-MSD-APP-00014 : Create HMS UI - Admin Home

- src/pages/projects/servicesavailpend.js
- src/styles/global.css
**Changes:**
- add Admin Services Available Pending Page
> DLS-MSD-APP-00015 : Create HMS UI - Admin Services - Available Pending

- src/pages/projects/servicesoutgoing.js
- src/styles/global.css
**Changes:**
-  add services outgoing page.
> DLS-MSD-APP-00017 : Create HMS UI - Admin Services - OutGoing

- src/pages/projects/servicescancelled.js
- src/styles/global.css
**Changes:**
- add services cancelled page
> DLS-MSD-APP-00018 : Create HMS UI - Admin Services - Cancelled

- src/pages/projects/index.js
**Changes:**
- Change styling source from global to projects
- add some correction for styling
- change internal links to proper
**For your review:** @raymundpaulfontanilla / @darrylkaye
> DLS-MSD-APP-00039 : MSD APP UI - FEATURE: Organize template and change style source for /projects/ route

- src/pages/projects/servicesavailpend.js
- src/styles/global.css
**Changes**
- fix warnings
- import css file
> DLS-MSD-APP-00035 : MSD APP UI - BUG: Resolve 2 issues with servicesavailpend.js

- src/pages/projects/home.js
- src/styles/global.css
**Changes**
- Fix home page 2 warnings.
> DLS-MSD-APP-00032 : MSD APP UI - BUG: Resolve 2 issues with home.js

- src/pages/projects/servicesoutgoing.js
- src/styles/global.css
**Changes**
- fix warnings
- import css file
> DLS-MSD-APP-00037 : MSD APP UI - BUG: Resolve 2 issues with servicesoutgoing.js

- src/pages/projects/servicesavailpend.js
- src/styles/global.css
**Changes**
- fix warnings
- remove chat
> DLS-MSD-APP-00036 : MSD APP UI - FEATURE: Provide revisions to servicesavailpend.js

- src/pages/projects/dashboard.js
- src/styles/projects.module.css
**Changes:**
- update project css from main
- apply project css to project dashboard
> DLS-MSD-APP-00040 : MSD APP UI - FEATURE: Organize template and change style source for /projects/dashboard/ route

- package-lock.json
- package.json
**Changes:**
- force install sweet alert 2
- execute `npm install -f sweetalert2`
- documentation : https://sweetalert2.github.io/
> DLS-MSD-APP-00056 : MSD WEBSITE - FEATURE: Install Sweet Alert 2

- package-lock.json
- package.json
- src/components/Hero.js
- src/components/Social.js
- src/pages/index.js
- src/styles/global.css
**Changes:**
- fix navbar shadow and AOS
> DLS-MSD-APP-00064 : MSD WEBSITE - fix index page styling

- package-lock.json
- package.json
- src/components/Header.js
- src/components/NavigationMenu.js
- src/pages/contact-us.js
- src/styles/contact-us.module.css
**Changes:**
- add boilerplate for /contact-us route pages
- correct all link for /contact-us route
- prepare local styling for /contact-us route
- add all content for /contact-us route
- force install @iconify-icons/ion
- force install @iconify-icons/bi
- fix rendering location and telephone icons
> DLS-MSD-APP-00055 : MSD WEBSITE - Create /contact-us/ route

- src/components/Hero.js
- src/styles/hero.module.css
**Changes:**
- add folder named components
- add hero component file
- migrate gatsby hero component to nextjs
- add styling for hero component
> DLS-MSD-APP-00077 : MSD WEBSITE - Migrate Hero Component  from Gatsby to NextJS

- src/components/Social.js
- src/styles/social.module.css
**Change(s):**
- add social component file
- migrate gatsby social component to nextjs
- add styling for social component
> DLS-MSD-APP-00078 : MSD WEBSITE - Migrate Social Component from Gatsby to NextJS

- src/app/components/footer/FooterIndex.js
- src/app/components/footer/Logo.js
- src/styles/footer.module.css
**Change(s):**
- add footer component file
- migrate gatsby footer component to nextjs
- add logo to footer component
- add styling for footer component
> DLS-MSD-APP-00080 : MSD WEBSITE - Migrate Footer Component from Gatsby to NextJS

- src/app/components/Hero.js
- src/app/components/Social.js
- src/app/components/header/index.js
- src/app/components/layout/index.js
- src/pages/index.js
**Change(s):**
- add layout component file
- fix relative path for hero and social and import of some component
> DLS-MSD-APP-0008 :  MSD WEBSITE - Migrate Layout Component from Gatsby to NextJS

- src/pages/about.js
- src/styles/about.module.css
**Changes:**
- add about module stylesheet
- add about route page
> DLS-MSD-APP-00071 : MSD WEBSITE - Migrate About page from Gatsby to NextJS

- src/pages/services/index.js
- src/styles/services.module.css
**Changes:**
- add services style sheet
- add services route module
> DLS-MSD-APP-00072 : MSD WEBSITE - Migrate Services page from Gatsby to NextJS

- src/app/components/navigation-menu/index.js
**Change(s):**
- add navigation-menu component
> DLS-MSD-APP-00082 : MSD WEBSITE - Migrate NavigationMenu Component from Gatsby to NextJS

- src/app/components/simple-layout/index.js
**Change(s):**
- add simple layout component
> DLS-MSD-APP-00083 : MSD WEBSITE - Migrate Simple Layout Component from Gatsby to NextJS

- src/app/components/navigation-menu/index.js
- src/app/components/simple-layout/index.js
- src/pages/services/single-bedroom.js
**Change(s):**
- add single bedroom page
- remove temporarily mdb-ui-kit javascript
> DLS-MSD-APP-00073 : MSD WEBSITE - Migrate Single bedroom page from Gatsby to NextJS

- src/pages/services/double-deck-bedroom.js
**Change(s):**
- add double deck bedroom page
- remove temporarily mdb-ui-kit javascript and simple layout
> DLS-MSD-APP-00074 : MSD WEBSITE - Migrate Double bedroom page from Gatsby to NextJS

- src/pages/contact-us.js
- src/styles/contact-us.module.css
**Change(s):**
- add styling for contact page
- add contact page
> DLS-MSD-APP-00075 : MSD WEBSITE - Migrate Contact Us page from Gatsby to NextJS

- package-lock.json
- package.json
- src/app/components/systems/hms/index.js
- src/pages/systems/hms/index.js
**Change(s):**
- install ant design
- create hms route
- implement HMS layout to HMS app
- add Splash component file
- add Login menu component
- add Dashboard component
- add Navigation bar component
- add Navigation Bar Header
- add Navigation Bar Filter component
- add Side Bar component
- add Application Title Bar
- add Side Bar Navigation
- add User Profile components
- add Footer component
- add Content component
> DLS-MSD-APP-00084 : MSD APP - Bootstrapping of hms dashboard

- src/app/components/Logo.js
- src/app/components/systems/hms/Splash.js
- src/app/components/systems/hms/index.js
- src/pages/systems/hms/index.js
- src/styles/splash.module.css
**Change(s):**
- add styling for splash component
- add splash component
- render splash component
- change title page and add favicon
> DLS-MSD-APP-00087 : Splash Screen Component

- src/app/components/systems/hms/LoginMenu.js
- src/pages/systems/hms/login.js
- src/styles/login.module.css
**Change(s):**
- add styling for logo component
- add logo component
- render logo component
> DLS-MSD-APP-00088 : Login Component

- src/app/components/systems/hms/Layout.js
- src/app/components/systems/hms/index.js
- src/styles/layout.module.css
**Change(s):**
- add styling for layout component
- add layout component
- render component to the index file
> DLS-MSD-APP-000100 : Layout Component

- src/app/components/systems/SplashListener.js
- src/app/components/systems/hms/Splash.js
**Change(s):**
- add splash listener component
- add splash function with event listener
> DLS-MSD-APP-00099 : Splash Screen Event Listener

- src/app/components/systems/hms/Dashboard.js
- src/pages/systems/hms/dashboard.js
**Change(s):**
- add dashboard component
- render dashboard component
> DLS-MSD-APP-00089 : Dashboard Component

- src/app/components/systems/hms/NavBarHeader.js
- src/styles/navbar-header.module.css
**Change(s):**
- add styling for navbar header component
- add navbar header component
> DLS-MSD-APP-00091 : Navigation Bar Header Component

- src/app/components/systems/hms/NavBarFilter.js
- src/styles/navbar-filter.module.css
**Change(s):**
- add styling for navbar filter component
- add navbar filter component
> DLS-MSD-APP-00092 : Navigation Bar Filter Component

- src/app/components/systems/hms/NavBarFilter.js
- src/styles/navbar-filter.module.css
**Change(s):**
- adjust margin left and right of the buttons
- adjust margin right and left of the drop down menu
> Forgotten to change the margin left and right

- src/app/components/systems/hms/NavBar.js
**Change(s):**
- add navbar component
> DLS-MSD-APP-00090 : Navigation Bar Component

- src/app/components/systems/hms/SideBarNavigation.js
**Change:**
- add sidebar navigation component
> DLS-MSD-APP-00095 : Side Bar Navigation

- src/app/components/systems/hms/AppTitleBar.js
**Change:**
- add app title bar component
> DLS-MSD-APP-00094 : Application Title Bar

- src/app/components/systems/hms/UserProfile.js
**Change:**
- add user profile component
> DLS-MSD-APP-00096 : User Profile Component

- src/app/components/systems/hms/SideBar.js
**Change:**
- add sidebar component
> DLS-MSD-APP-00093 : Side Bar Component

- src/app/components/systems/hms/Footer.js
**Change:**
- add footer layout component
> DLS-MSD-APP-00097 : Footer Component

- api/hms/app.py
- api/hms/app/controllers/user_controller.py
- api/hms/config.py
- api/hms/requirements.txt
- package-lock.json
- package.json
- src/app/components/systems/hms/LoginMenu.js
**Change(s):**
- add axios package
- add flask-cors in the requirements
- add os library and cors origins in the config.py
- add flask cors library in the main app.py
- change get to post request in the user controller
- migrate login form from gatsby to nextjs and add simple validation
> DLS-MSD-APP-000101 : Migrate login form validation page from Gatsby to NextJS

- src/app/components/systems/hms/NotFound.js
- src/styles/not-found.module.css
**Change(s):**
- add styling for not found component
- add not found component
> DLS-MSD-APP-00056 : MSD WEBSITE - 404.js

- src/app/components/systems/hms/UserProfile.js
**Change(s):**
- import use router
- add logout session
> DLS-MSD-APP-000102 : Logout Component

- src/app/components/systems/hms/LoginMenu.js
- src/app/components/systems/hms/UserProfile.js
**Change(s):**
- add useEffect to use session storage
- change the user token into username for removing the session storage
> DLS-MSD-APP-00105 : Display name in the user profile component

- package-lock.json
- package.json
- src/app/components/bin/CardsData.js
- src/app/components/loading.js
- src/app/components/systems/hms/DragAndDrop.js
- src/app/components/systems/hms/Layout.js
- src/app/components/systems/hms/LoadingSkeleton.js
- src/context/DNDContext.js
- src/styles/drag-and-drop.module.css
**Change(s):**
- add react beautiful dnd and loading skeleton package
- add sample data to use as draggable cards
- add drag and drop context
- rename back to its original name
- add loading skeleton library
- render loading skeleton component and its library
- add styling for drag and drop component
- add drag and drop component
- render drag and drop component
> DLS-MSD-APP-00098 : Draggable Card Component

- src/app/components/systems/hms/Calendar.js
- src/app/components/systems/hms/GuestModal.js
- src/app/components/systems/hms/NavBarFilter.js
- src/app/components/systems/hms/RoomRateUtils.js
**Change(s):**
- add guest form component
- add room rate component
- add date picker component
- add modal and render the guest modal  component
> DLS-MSD-APP-00108: Modal Component for Guest Form

- api/hms/app/controllers/guest_controller.py
- api/hms/app/models/guest_model.py
- api/hms/app/views/guest_view.py
- api/hms/routes.py
**Change(s):**
- add model for adding guest
- refactor MVC and route by using dynamic
- add new controller for adding guest
- add view for adding guest
- add route for adding guest
> DLS-MSD-APP-00112 : Create Resource for Adding Guest
